<TrainScreen>:
  name: 'train_scr'
  BoxLayout:
    orientation: 'vertical'
#    ProgressBar:
#      id:progress_bar
#      # size_hint_x:.5
#      size_hint_y:None
#      height:'5dp'
#      # value:(app.time*20)%100
    Splitter:
      size_hint_y: None
      height: dp(500)
      sizable_from: 'bottom'
      FloatLayout:
        id: training_pannel
    BoxLayout:
      orientation: 'vertical'
      ScreenManager:
        id:display_screens
