#: import os os
<FileChooserDialog>:
  BoxLayout:
    size: root.size
    pos: root.pos
    orientation: "vertical"
#    FileChooserIconView:
    FileChooserListView:
      id: filechooser
      filters: root.filters
      path: os.getcwd()

    BoxLayout:
      size_hint_y: None
      height: 30
      Button:
        text: "Cancel"
        on_release: root.cancel()

      Button:
        text: "Select"
        on_release: root.select(filechooser.path, filechooser.selection, root.text_info)
